---

- name: Handle prerequisite jobs
  hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- name: Deploy k3s master node
  hosts: master
  become: yes
  roles:
    - role: k3s/master

- name: Deploy k3s worker node
  hosts: node
  become: yes
  roles:
    - role: k3s/node
