---
- name: Add SSH keys
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Add Personal SSH keys
      ansible.posix.authorized_key:
        user: jack
        state: present
        key: https://github.com/SpringheeledJT.keys
        comment: Personal SSH key

    - name: Add Work SSH keys
      ansible.posix.authorized_key:
        user: jack
        state: present
        key: https://github.com/JackTovey.keys
        comment: Work SSH key

    - name: Enable ssh key auth
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "#PubkeyAuthentication (yes|no)"
        line: "PubkeyAuthentication yes"
        state: present

    - name: Disable password auth
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "#PasswordAuthentication (yes|no)"
        line: "PasswordAuthentication yes"
        state: present

    - name: Disable root login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "#PermitRootLogin (prohibit-password|yes)"
        line: "PermitRootLogin no"
        state: present

    - name: Restart sshd
      ansible.builtin.systemd_service:
        name: sshd
        state: restarted
